[package]
name = "lazarus"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
async-trait = "0.1"

[lib]
name = "lazarus"
path = "src/lib.rs"
