[package]
name = "prism"
version = "0.4.0"
edition = "2021"

[dependencies]
# We added "visit" to features
syn = { version = "2.0", features = ["full", "extra-traits", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"
anyhow = "1.0"

[lib]
name = "prism"
path = "src/lib.rs"
